name: Build iOS IPA
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup CocoaPods
        run: |
          pod repo update
          if [ -f "Podfile" ]; then pod install; fi

      - name: Find and Build Xcode Project
        run: |
          WORKSPACE_FILE=$(find . -name "*.xcworkspace" | head -n 1)
          if [ -z "$WORKSPACE_FILE" ]; then
            WORKSPACE_FILE=$(find . -name "*.xcodeproj" | head -n 1)
            BUILD_CMD="-project $WORKSPACE_FILE"
          else
            BUILD_CMD="-workspace $WORKSPACE_FILE"
          fi
          
          SCHEME_NAME=$(xcodebuild -list -json | json_pp | grep -m 1 '"schemes"' -A 1 | tail -n 1 | tr -d '" ,')
          echo "Selected Scheme: $SCHEME_NAME"
          
          xcodebuild $BUILD_CMD -scheme "$SCHEME_NAME" -configuration Release -sdk iphoneos ALLOW_PROVISIONING_PROFILE_REQUIRED=NO ALLOW_PROVISIONING_DEVICE_REGISTRATION_REQUIRED=NO CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO COMPILER_INDEX_STORE_ENABLE=NO clean archive -archivePath build/VoidLink.xcarchive

      - name: Extract App and Packaging
        run: |
          mkdir -p build/Payload
          APP_PATH=$(find build/VoidLink.xcarchive/Products/Applications -name "*.app" | head -n 1)
          cp -r "$APP_PATH" build/Payload/
          cd build && zip -r VoidLink_unsigned.ipa Payload

      - name: Upload Finished IPA
        uses: actions/upload-artifact@v4
        with:
          name: VoidLink-Unsigned-IPA
          path: build/VoidLink_unsigned.ipa


